# Practice Exam 1 Question 11

### Import Libraries

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 

### Class to Create a Neural Network With Single Neuron 

In [2]:
class NeuralNetwork(object):  
     
    def __init__(self, num_params = 4):  
        # Using seed to make sure it'll generate same weights in every run  
        # np.random.seed(1)  
        
        # 3x1 Weight matrix
        # random weights between -1 and 1 
        self.weight_matrix = 2 * np.random.random((num_params + 1, 1)) - 1
        self.l_rate = 1 
   
    # hard_limiter as activation fucntion  
    def hard_limiter(self, x): 
        outs = np.zeros(x.shape) 
        outs[x > 0] = 1 
        return outs 
   
    # forward propagation  
    def forward_propagation(self, inputs): 
        outs = np.dot(inputs, self.weight_matrix) 
        return self.hard_limiter(outs)  
       
    # training the neural network.  
    def train(self, train_inputs, train_outputs, num_train_iterations = 1000):                       
        # Number of iterations we want to perform for this set of input.  
        for iteration in range(num_train_iterations): 
            # updating the perceptron base on the misclassified examples 
            for i in range(train_inputs.shape[0]): 
              pred_i = self.pred(train_inputs[i,:])  
              if pred_i != train_outputs[i]: 
                output = self.forward_propagation(train_inputs[i,:])  
                # Calculate the error in the output.  
                error = train_outputs[i] - output  
                adjustment = self.l_rate * error * train_inputs[i]                        
                # Adjust the weight matrix  
                self.weight_matrix[:,0] += adjustment
    
    # predicting the classes of new data points 
    def pred(self,inputs): 
      preds = self.forward_propagation(inputs) 
      return preds

### Declare Features and Labels

In [3]:
features = np.array([[3,3,0.5,1], [2.5,1.5,1.5,-1], [0.5,1.5,-1,0], [1,1,1,-3]])
print(features, '\n')

labels = np.array([0,1,1,0]) 
print(labels)

classes = [0, 1] 

[[ 3.   3.   0.5  1. ]
 [ 2.5  1.5  1.5 -1. ]
 [ 0.5  1.5 -1.   0. ]
 [ 1.   1.   1.  -3. ]] 

[0 1 1 0]


### Create Bias Vector and Append to Features

In [4]:
bias = np.ones((features.shape[0], 1)) # expanding the feature space by adding  
print(bias, '\n') 
print(bias.shape, '\n') 
features = np.append(bias, features, axis = 1) 
print(features, '\n')
print(features.shape)

[[1.]
 [1.]
 [1.]
 [1.]] 

(4, 1) 

[[ 1.   3.   3.   0.5  1. ]
 [ 1.   2.5  1.5  1.5 -1. ]
 [ 1.   0.5  1.5 -1.   0. ]
 [ 1.   1.   1.   1.  -3. ]] 

(4, 5)


### Declare a NeuralNetwork Object to Test Random Weighting

In [5]:
neural_network = NeuralNetwork() 

print ('Random weights at the start of training') 
print (neural_network.weight_matrix) 

Random weights at the start of training
[[-0.58303805]
 [-0.01177172]
 [-0.82886102]
 [-0.26357025]
 [ 0.83753936]]


### Declare a NeuralNetwork object for Classification

In [6]:
neural_network = NeuralNetwork(4) 

print ('Random weights at the start of training') 
print (neural_network.weight_matrix)

Random weights at the start of training
[[-0.8198831 ]
 [ 0.2067343 ]
 [-0.90983538]
 [ 0.55572428]
 [ 0.86322521]]


### Train NeuralNetwork Object

In [7]:
neural_network.train(features, labels, 10)
print ('New Weights at the End of Training') 
print (neural_network.weight_matrix)

New Weights at the End of Training
[[ 3.1801169 ]
 [ 1.7067343 ]
 [-2.40983538]
 [-0.94427572]
 [ 1.86322521]]


### Test Neural Network with Training Data Points. 

In [8]:
print ("Test Network on Training Data Points:") 
print (neural_network.pred(features))

Test Network on Training Data Points:
[[1.]
 [1.]
 [1.]
 [0.]]
